language: java

jdk:
- oraclejdk8

branches:
  only:
  - master

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn package

before_deploy:
- if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[unstable]" ; then echo "skipping travis deploy" && exit 0 ; fi
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_KEY}:@github.com" > .git/credentials
- git push -q origin HEAD:$TRAVIS_BRANCH --follow-tags
- if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[recommended]" ;
  then export GITHUB_DEPLOY_PRERELEASE=false;
  else export GITHUB_DEPLOY_PRERELEASE=true;
  fi
- echo $GITHUB_DEPLOY_PRERELEASE
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: $GITHUB_DEPLOY_PRERELEASE
  api_key: $GITHUB_KEY
  file_glob: true
  file: 'target/*.jar'
  body: 'Deathmoney build $TRAVIS_BUILD_NUMBER for spigot $TRAVIS_BRANCH'
  on:
    tags: false
    branch: master