name: Deathmoney
version: 0.5
main: com.imyvm.spigot.plugin.main.PluginMain
depend: [Vault, NyaaCore]
softdepend:
- RPGItems
api-version: 1.13
commands:
  custom:
    description: All commands
    aliases: [cm, c]
  checker:
    description: rpg
    aliases: ch
  imyvmcommand:
    description: design for imyvm policeman or policewoman
    aliases: [imc, imyvm]
  freeze:
    description: tools
    aliases: [fr]
  unfreeze:
    description: tools
    aliases: [unfr]
permissions:
  custom.*:
    children:
      custom.add: true
      custom.revoke: true
  checker.*:
    childeren:
      checker.take: true
  ic.command.*:
    childeren:
      ic.command.tp: true
      ic.command.fly: true