name: Deathmoney
version: 0.4
main: com.imyvm.spigot.plugin.main.PluginMain
depend: [Vault]
api-version: 1.13

commands:
  deathmoney:
    description: /deathmoney reload
    aliases: []
permissions:
  deathmoney.*:
    children:
      deathmoney.reload: true
      deathmoney.bypass: true