name: Deathmoney
version: 0.3
main: com.imyvm.spigot.plugin.main.PluginMain
depend: [Vault]

commands:
  deathmoney:
    description: /deathmoney reload
    aliases: []
permissions:
  deathmoney.*:
    children:
      deathmoney.reload: true
      deathmoney.bypass: true